# Generated by Django 5.2.5 on 2025-09-15 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Kurs", "verbose_name_plural": "Kurslar"},
        ),
        migrations.AlterField(
            model_name="course",
            name="practice_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.DecimalField(db_default=0, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="course",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.topic",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_duration",
            field=models.IntegerField(db_default=0),
        ),
    ]
